In [1]:
from entsoe import EntsoePandasClient
from dotenv import dotenv_values

import pandas as pd

config = dotenv_values(".env")

client = EntsoePandasClient(api_key=config["TRANSPARENCY_API_TOKEN"])

start = pd.Timestamp('20250829', tz='Europe/Brussels')
end = pd.Timestamp('20250830', tz='Europe/Brussels')
country_code = 'CZ'

In [2]:
client.query_generation(country_code, start=start, end=end, psr_type=None)

                                    Biomass Fossil Brown coal/Lignite  \
                          Actual Aggregated         Actual Aggregated
2025-08-29 00:00:00+02:00             376.0                    3230.0
2025-08-29 00:15:00+02:00             376.0                    3243.0
2025-08-29 00:30:00+02:00             376.0                    3283.0
2025-08-29 00:45:00+02:00             375.0                    3307.0
2025-08-29 01:00:00+02:00             375.0                    3337.0
...                                     ...                       ...
2025-08-29 22:45:00+02:00             373.0                    3328.0
2025-08-29 23:00:00+02:00             371.0                    3275.0
2025-08-29 23:15:00+02:00             369.0                    3273.0
2025-08-29 23:30:00+02:00             371.0                    3210.0
2025-08-29 23:45:00+02:00             370.0                    3086.0

                          Fossil Coal-derived gas        Fossil Gas  \
                                Actual Aggregated Actual Aggregated
2025-08-29 00:00:00+02:00                     0.0              95.0
2025-08-29 00:15:00+02:00                     0.0              95.0
2025-08-29 00:30:00+02:00                     0.0              94.0
2025-08-29 00:45:00+02:00                     0.0              94.0
2025-08-29 01:00:00+02:00                     0.0             117.0
...                                           ...               ...
2025-08-29 22:45:00+02:00                     0.0             110.0
2025-08-29 23:00:00+02:00                     0.0             102.0
2025-08-29 23:15:00+02:00                     0.0             101.0
2025-08-29 23:30:00+02:00                     0.0             123.0
2025-08-29 23:45:00+02:00                     0.0             102.0

                           Fossil Hard coal        Fossil Oil  \
                          Actual Aggregated Actual Aggregated
2025-08-29 00:00:00+02:00               8.0               0.0
2025-08-29 00:15:00+02:00              10.0               0.0
2025-08-29 00:30:00+02:00              12.0               0.0
2025-08-29 00:45:00+02:00              10.0               0.0
2025-08-29 01:00:00+02:00               8.0               0.0
...                                     ...               ...
2025-08-29 22:45:00+02:00              15.0               0.0
2025-08-29 23:00:00+02:00              14.0               0.0
2025-08-29 23:15:00+02:00              11.0               0.0
2025-08-29 23:30:00+02:00              11.0               0.0
2025-08-29 23:45:00+02:00              11.0               0.0

                          Hydro Pumped Storage                     \
                             Actual Aggregated Actual Consumption
2025-08-29 00:00:00+02:00                 75.0                0.0
2025-08-29 00:15:00+02:00                 72.0                0.0
2025-08-29 00:30:00+02:00                 30.0                0.0
2025-08-29 00:45:00+02:00                  0.0                0.0
2025-08-29 01:00:00+02:00                  0.0                0.0
...                                        ...                ...
2025-08-29 22:45:00+02:00                158.0                0.0
2025-08-29 23:00:00+02:00                  0.0                0.0
2025-08-29 23:15:00+02:00                  0.0                0.0
2025-08-29 23:30:00+02:00                  0.0                0.0
2025-08-29 23:45:00+02:00                  0.0                0.0

                          Hydro Run-of-river and poundage  \
                                        Actual Aggregated
2025-08-29 00:00:00+02:00                            55.0
2025-08-29 00:15:00+02:00                            57.0
2025-08-29 00:30:00+02:00                            57.0
2025-08-29 00:45:00+02:00                            57.0
2025-08-29 01:00:00+02:00                            58.0
...                                                   ...
2025-08-29 22:45:00+02:00                            46.0
2025-08-29 23:00:00+02:00                            49.0
2025-08-29 23:15:00+02:00                            50.0
2025-08-29 23:30:00+02:00                            50.0
2025-08-29 23:45:00+02:00                            49.0

                          Hydro Water Reservoir           Nuclear  \
                              Actual Aggregated Actual Aggregated
2025-08-29 00:00:00+02:00                  30.0            3891.0
2025-08-29 00:15:00+02:00                  19.0            3892.0
2025-08-29 00:30:00+02:00                  19.0            3894.0
2025-08-29 00:45:00+02:00                  18.0            3897.0
2025-08-29 01:00:00+02:00                  12.0            3898.0
...                                         ...               ...
2025-08-29 22:45:00+02:00                  77.0            3428.0
2025-08-29 23:00:00+02:00                  41.0            3427.0
2025-08-29 23:15:00+02:00                  39.0            3427.0
2025-08-29 23:30:00+02:00                  39.0            3430.0
2025-08-29 23:45:00+02:00                  46.0            3432.0

                                      Other   Other renewable  \
                          Actual Aggregated Actual Aggregated
2025-08-29 00:00:00+02:00              37.0             251.0
2025-08-29 00:15:00+02:00              37.0             251.0
2025-08-29 00:30:00+02:00              37.0             252.0
2025-08-29 00:45:00+02:00              37.0             251.0
2025-08-29 01:00:00+02:00              37.0             251.0
...                                     ...               ...
2025-08-29 22:45:00+02:00              34.0             255.0
2025-08-29 23:00:00+02:00              35.0             254.0
2025-08-29 23:15:00+02:00              36.0             253.0
2025-08-29 23:30:00+02:00              36.0             254.0
2025-08-29 23:45:00+02:00              36.0             254.0

                                      Solar             Waste  \
                          Actual Aggregated Actual Aggregated
2025-08-29 00:00:00+02:00               0.0              31.0
2025-08-29 00:15:00+02:00               0.0              31.0
2025-08-29 00:30:00+02:00               0.0              31.0
2025-08-29 00:45:00+02:00               0.0              31.0
2025-08-29 01:00:00+02:00               0.0              31.0
...                                     ...               ...
2025-08-29 22:45:00+02:00               0.0              30.0
2025-08-29 23:00:00+02:00               0.0              30.0
2025-08-29 23:15:00+02:00               0.0              30.0
2025-08-29 23:30:00+02:00               0.0              30.0
2025-08-29 23:45:00+02:00               0.0              30.0

                               Wind Onshore
                          Actual Aggregated
2025-08-29 00:00:00+02:00              45.0
2025-08-29 00:15:00+02:00              34.0
2025-08-29 00:30:00+02:00              34.0
2025-08-29 00:45:00+02:00              32.0
2025-08-29 01:00:00+02:00              40.0
...                                     ...
2025-08-29 22:45:00+02:00              34.0
2025-08-29 23:00:00+02:00              38.0
2025-08-29 23:15:00+02:00              49.0
2025-08-29 23:30:00+02:00              61.0
2025-08-29 23:45:00+02:00              65.0

[96 rows x 16 columns]

In [3]:
client.query_load(country_code, start=start, end=end)

                           Actual Load
2025-08-29 00:00:00+02:00       5512.0
2025-08-29 00:15:00+02:00       5463.0
2025-08-29 00:30:00+02:00       5477.0
2025-08-29 00:45:00+02:00       5462.0
2025-08-29 01:00:00+02:00       5441.0
...                                ...
2025-08-29 22:45:00+02:00       5562.0
2025-08-29 23:00:00+02:00       5474.0
2025-08-29 23:15:00+02:00       5406.0
2025-08-29 23:30:00+02:00       5333.0
2025-08-29 23:45:00+02:00       5209.0

[96 rows x 1 columns]